### PR TITLE
Fixes Sum call response; resolves #821, resolves #822

### LINKED ISSUE #821: Replace Sum and Average calls with SumCount call
### Description

When the response is JSON, `Average` call returns a single integer even though the result may be a float. This is problematic, since the result is not correct, and also the user has no control over the conversion of the float to integer.

Meanwhile, in the protobuf response there are two fields: `Sum` and `Count` instead of the single integer. `Sum` and `Average` returns the same result!

In order to resolve these problems, we can have a `SumReduce` call which returns `Sum` and `Count` fields. That would be easier to implement than the other option: returning floats for `Average` and returning floats (or integers) from the `Sum` call.

**EDIT**
The protobuf result has the `SumCount` field which has a `Count` field of type `int64`. The result also has the `N` field which is of type `uint64`. That is confusing. We can remove the `SumCount` field from the result, and add a `Sum` field which is `int64`. The `N` field would be used in place of `Count`.

**EDIT 2**
See: https://github.com/pilosa/pilosa/issues/822 for a related issue.

**EDIT 3**
Renamed `SumCount` call to `SumReduce`.

### LINKED ISSUE #822: Protobuf response for Average and Sum calls is broken
### Expected behavior

The protobuf results for `Average` and `Sum` queries should have their `SumCount` field set accordingly.

### Actual behavior

`SumCount` field for protobuf results for `Average` and `Sum` queries is `nil`.

This happens because `handler.encodeQueryResponse` function receives `int64` results for `Average` and `Sum` instead of `SumCount`. So the `case SumCount:` statement around line 1514 doesn't get run which results in `pb.Results[i].SumCount == nil`.

### PR DESCRIPTION
**Pull request by yuce**
## Overview

Fixed Sum call to return SumCount; removed Average call.

Fixes #821, #822

## Pull request checklist

- [x] I have read the [contributing guide](https://github.com/pilosa/pilosa/blob/master/CONTRIBUTING.md).
- [x] I have agreed to the [Contributor License Agreement](https://cla-assistant.io/pilosa/pilosa).
- [ ] I have updated the [documentation](https://github.com/pilosa/pilosa/tree/master/docs).
- [x] I have resolved any merge conflicts.
- [ ] I have included tests that cover my changes.
- [x] All new and existing tests pass.

## Code review checklist
This is the checklist that the reviewer will follow while reviewing your pull request. You do not need to do anything with this checklist, but be aware of what the reviewer will be looking for.

- [ ] Ensure that any changes to external docs have been included in this pull request.
- [ ] If the changes require that minor/major versions need to be updated, tag the PR appropriately.
- [ ] Ensure the new code is [properly commented](https://github.com/golang/go/wiki/CodeReviewComments#doc-comments) and follows [Idiomatic Go](https://dmitri.shuralyov.com/idiomatic-go).
- [ ] Check that tests have been written and that they cover the new functionality.
- [ ] Run tests and ensure they pass.
- [ ] Build and run the code, performing any applicable integration testing.

### CODE REVIEW

**Comment by yuce** [comment]
This should be ready to review. Although since Sum call can cause an overflow in the `SumCount.Sum` field, we should remove it or increase the size of `SumCount.Sum` to 128 bits (protobuf doesn't support it, so we would have to store it as 2 int64s)

File: executor_test.go [hunk 1]
```diff
@@ -600,8 +600,8 @@ func TestExecutor_Execute_TopN_Attr_Src(t *testing.T) {
 	}
 }
 
-// Ensure a Sum() query can be executed.
-func TestExecutor_Execute_Sum(t *testing.T) {
+// Ensure a SumReduce() query can be executed.
```
Comment (travisturner) [inline executor_test.go]: Should we change this test name and comment back to `Sum` instead of `SumReduce`?
