### PR TITLE
Default BSI base value to min, max, or 0 depending on the min/max range

### LINKED ISSUE #2013: int range bug in Pilosa
### What's going wrong?

Wrong answer on range query. See steps below:

```
Fri 06/14 11:44:46:~()$ curl localhost:10101/index/bla -d'{}'
{"success":true}
Fri 06/14 11:48:15:~()$ curl localhost:10101/index/bla/field/aint -d'{"options": {"type": "int", "min": -9223372036854775808, "max": 9223372036854775807}}'
{"success":true}
Fri 06/14 11:48:34:~()$ curl localhost:10101/index/bla/query -d'Set(10, aint=11) Set(100, aint=15)'
{"results":[true,true]}
Fri 06/14 11:48:43:~()$ curl localhost:10101/index/bla/query -d'Row(aint > 100)'
]{"results":[{"attrs":{},"columns":[10,100]}]}
```

### What was expected?
the two values for field aint are 11 and 15 so aint > 100 should return no columns.

### Information about your environment (OS/architecture, CPU, RAM, cluster/solo, configuration, etc.)

This is happening in go-pilosa CI tests, and also on my Mac locally. 1.3.0 and v1.3.1

### PR DESCRIPTION
**Pull request by travisturner**
## Overview

The BSI base value determined by `FieldOptions.Base` was defaulting to 0 (except in cases of migration from v1 of BSI). This PR changes the logic to set the `base` to either min, max, or 0 depending on the range of min/max.

Fixes #2013 

## Pull request checklist

- [x] I have read the [contributing guide](https://github.com/pilosa/pilosa/blob/master/CONTRIBUTING.md).
- [x] I have agreed to the [Contributor License Agreement](https://cla-assistant.io/pilosa/pilosa).
- [ ] I have updated the [documentation](https://github.com/pilosa/pilosa/tree/master/docs).
- [x] I have resolved any merge conflicts.
- [x] I have included tests that cover my changes.
- [x] All new and existing tests pass.
- [x] Make sure PR title conforms to convention in CHANGELOG.md.
- [x] Add appropriate changelog label to PR (if applicable).

## Code review checklist
This is the checklist that the reviewer will follow while reviewing your pull request. You do not need to do anything with this checklist, but be aware of what the reviewer will be looking for.

- [ ] Ensure that any changes to external docs have been included in this pull request.
- [ ] If the changes require that minor/major versions need to be updated, tag the PR appropriately.
- [ ] Ensure the new code is [properly commented](https://github.com/golang/go/wiki/CodeReviewComments#doc-comments) and follows [Idiomatic Go](https://dmitri.shuralyov.com/idiomatic-go).
- [ ] Check that tests have been written and that they cover the new functionality.
- [ ] Run tests and ensure they pass.
- [ ] Build and run the code, performing any applicable integration testing.
- [ ] Make sure PR title conforms to convention in CHANGELOG.md.
- [ ] Make sure PR is tagged with appropriate changelog label.

### CODE REVIEW

**Comment by travisturner** [comment]
I just realized we may need to apply this same logic to the migration code in `Field.loadMeta()` as well.

**Comment by travisturner** [comment]
I pushed another commit to apply that same logic to the migration from v1 code.

File: field.go [hunk 1]
```diff
@@ -499,7 +508,13 @@ func (f *Field) loadMeta() error {
...
 	// Initialize "base" to "min" when upgrading from v1 BSI format.
 	if pb.BitDepth == 0 {
-		pb.Base = pb.Min
+		if pb.Min > 0 {
+			pb.Base = pb.Min
+		} else if pb.Max < 0 {
+			pb.Base = pb.Max
+		} else {
+			pb.Base = 0
+		}
```
Comment (benbjohnson) [inline field.go]: One minor improvement might be to make a `bsiBase(min, max uint64) uint64` that contains the logic since it's duplicated.

Comment (travisturner) [reply field.go]: good idea. i just pushed 96e6c1189793a8981938b767cbb6f1b389985362 with that change.
