### PR TITLE
Row id zero bug

### LINKED ISSUE #809: input definition assumes 0 for non-existent fields, sets unexpected bits
### Expected behavior
If a field is not present in a record sent to the input definition, for example the "stargazer_id" field, no bit would be set in the corresponding frame (stargazers).

### Actual behavior
A value of 0 is assumed for the missing field (at least in the case of stargazer_id, and the bit is set in that row.

### Steps to reproduce the behavior
Follow the input definition docs.

### Information about your environment (OS/architecture, CPU, RAM, cluster/solo, configuration, etc.)
Macbook Pro single node cluster.

### PR DESCRIPTION
**Pull request by linhvo**
## Overview

[Describe what this pull request addresses.]

Fixes #809 
add a test and some tests refactor using driven table test

## Pull request checklist

- [ ] I have read the [contributing guide](https://github.com/pilosa/pilosa/blob/master/CONTRIBUTING.md).
- [ ] I have agreed to the [Contributor License Agreement](https://cla-assistant.io/pilosa/pilosa).
- [ ] I have updated the [documentation](https://github.com/pilosa/pilosa/tree/master/docs).
- [ ] I have resolved any merge conflicts.
- [ ] I have included tests that cover my changes.
- [ ] All new and existing tests pass.

## Code review checklist
This is the checklist that the reviewer will follow while reviewing your pull request. You do not need to do anything with this checklist, but be aware of what the reviewer will be looking for.

- [ ] Ensure that any changes to external docs have been included in this pull request.
- [ ] If the changes require that minor/major versions need to be updated, tag the PR appropriately.
- [ ] Ensure the new code is [properly commented](https://github.com/golang/go/wiki/CodeReviewComments#doc-comments) and follows [Idiomatic Go](https://dmitri.shuralyov.com/idiomatic-go).
- [ ] Check that tests have been written and that they cover the new functionality.
- [ ] Run tests and ensure they pass.
- [ ] Build and run the code, performing any applicable integration testing.

### CODE REVIEW

File: input_definition.go [hunk 1]
```diff
@@ -372,7 +371,7 @@ func HandleAction(a Action, value interface{}, colID uint64, timestamp int64) (*
 		}
 		bit.RowID = uint64(v)
 	case InputSetTimestamp:
```
Comment (raskle) [inline input_definition.go]: I think we should add a comment about where the timestamp is handled earlier, and why we need to return nil.

Comment (raskle) [reply input_definition.go]: how about:
//  InputSetTimestamp action is used in the InputJSONDataParser Handler to append a timestamp to all bits in the frame. There are no individual rowID's to set, and the action is a no-op at this step.
