### PR TITLE
Validate /fragment/nodes arguments. Fixes #652

### LINKED ISSUE #652: /fragment/nodes should validate query arguments
### Expected behavior

I would expect `/fragment/nodes?slice=0&db=somedb` to return an error, like: `db is not a valid query argument`

### Actual behavior

`[{"host":":10101","internalHost":""}]` was returned, instead of an error.

### Steps to reproduce the behavior

`curl localhost:10101/fragment/nodes?slice=0&db=myindex`

### PR DESCRIPTION
**Pull request by yuce**
## Overview

This PR adds query argument validation to all relevant handlers (taking query arguments).

Fixes #652 

## Pull request checklist

- [x] I have read the [contributing guide](https://github.com/pilosa/pilosa/blob/master/CONTRIBUTING.md).
- [x] I have agreed to the [Contributor License Agreement](https://cla-assistant.io/pilosa/pilosa).
- [ ] I have updated the [documentation](https://github.com/pilosa/pilosa/tree/master/docs).
- [x] I have resolved any merge conflicts.
- [x] I have included tests that cover my changes.
- [x] All new and existing tests pass.

## Code review checklist
This is the checklist that the reviewer will follow while reviewing your pull request. You do not need to do anything with this checklist, but be aware of what the reviewer will be looking for.

- [ ] Ensure that any changes to external docs have been included in this pull request.
- [ ] If the changes require that minor/major versions need to be updated, tag the PR appropriately.
- [ ] Ensure the new code is [properly commented](https://github.com/golang/go/wiki/CodeReviewComments#doc-comments) and follows [Idiomatic Go](https://dmitri.shuralyov.com/idiomatic-go).
- [ ] Check that tests have been written and that they cover the new functionality.
- [ ] Run tests and ensure they pass.
- [ ] Build and run the code, performing any applicable integration testing.

### CODE REVIEW

**Comment by travisturner** [comment]
I like the direction of this, but I wonder if there's a more succinct way to define validators and prevent excessive code? For example, it seems like the validation code added to `handleGetFragmentNodes()` could be avoided. Perhaps creating/registering a [gorilla/mux middleware](https://github.com/gorilla/mux#middleware) validator would be a cleaner approach?

**Comment by yuce** [comment]
I think that's a great idea, I'll see how I can use the gorilla middleware.

**Comment by yuce** [comment]
@travisturner I've added a gorilla/mux middleware for validation (requires the latest gorilla/mux). Changed how a validator is created and attached to validators, so validators can be defined in a single line:
```go
h.validators["GET /fragment/nodes"] = QueryValidationSpecRequired("slice").Optional("index")
```

`QueryValidationSpecRequired` is still a long function name, I can rename to be shorter.

**Comment by yuce** [comment]
I've changed how the key for a validator is found (otherwise it isn't possible to match handlers with dynamic paths). I've applied validation to all handlers taking query arguments.

File: handler.go [hunk 1]
```diff
@@ -2057,3 +2084,41 @@ func (h *Handler) handleGetID(w http.ResponseWriter, r *http.Request) {
 }
 
 type defaultClusterMessageResponse struct{}
+
+type queryValidationSpec struct {
+	required []string
+	args     map[string]bool
```
Comment (travisturner) [inline handler.go]: If you aren't going to use the `bool` value for anything, this could be `map[string]struct{}`.

File: handler.go [hunk 2]
```diff
@@ -2057,3 +2084,41 @@ func (h *Handler) handleGetID(w http.ResponseWriter, r *http.Request) {
...
+}
+
+func QueryValidationSpecRequired(requiredArgs ...string) *queryValidationSpec {
```
Comment (travisturner) [inline handler.go]: What do you think about splitting this into `NewQueryValidationSpec()` and `Required()`?
Then we could define something like:
```
h.validators["GET /some/path"] = NewQueryValidationSpec().Optional("index")
h.validators["GET /other/path"] = NewQueryValidationSpec().Required("frame")
```

File: handler.go [hunk 3]
```diff
@@ -91,9 +95,30 @@ func NewHandler() *Handler {
...
+	h.validators["GET /fragment/nodes"] = QueryValidationSpecRequired("slice").Optional("index")
+}
+
+func (h *Handler) queryArgValidator(next http.Handler) http.Handler {
+	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
+		key := fmt.Sprintf("%s %s", r.Method, r.URL.Path)
+		if validator, ok := h.validators[key]; ok {
+			q := r.URL.Query()
+			err := validator.validate(q)
+			if err != nil {
```
Comment (travisturner) [inline handler.go]: how about: `if err := validator.validate(r.URL.Query()); err != nil {`

File: handler.go [hunk 4]
```diff
@@ -85,28 +89,67 @@ var externalPrefixFlag = map[string]bool{
...
+	h.validators["PostFrameRestore"] = QueryValidationSpecRequired("host")
+}
+
+func (h *Handler) queryArgValidator(next http.Handler) http.Handler {
+	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
+		key := mux.CurrentRoute(r).GetName()
+		if validator, ok := h.validators[key]; ok {
+			q := r.URL.Query()
+			err := validator.validate(q)
+			if err != nil {
```
Comment (travisturner) [inline handler.go]: how about: `if err := validator.validate(r.URL.Query()); err != nil {`

File: handler.go (hunk 1 above)
Comment (yuce) [reply handler.go]: ok

File: handler.go (hunk 2 above)
Comment (yuce) [reply handler.go]: Actually it was that way before, but I've changed it to make it look a bit better:
```go
QueryValidationSpecRequired("index").Optional("frame")
```
instead of
```go
QueryValidationSpec().Required("index").Optional("frame")
```
I like the current way better, but I can change it to another style.

File: handler.go (hunk 3 above)
Comment (yuce) [reply handler.go]: ok

File: handler.go (hunk 4 above)
Comment (yuce) [reply handler.go]: ok

File: handler.go (hunk 2 above)
Comment (travisturner) [reply handler.go]: No need to change it. This was just a suggestion.

**Comment by yuce** [comment]
Updated
