### PR TITLE
ensure mutex imports unset previous columns

### LINKED ISSUE #1652: Import into mutex and bool fields allow conflicting data.
### Expected behavior
Importing into a `mutex` or `bool` field, for a specific column, will clear any existing values (in other rows) for that column.

### Actual behavior
The import sub-command allows data to be imported into any row of the field.

### Steps to reproduce the behavior
```
curl -X POST http://localhost:10101/index/i -d '{"options": {}}'
curl -X POST http://localhost:10101/index/i/field/f -d '{"options": {"type": "bool"}}'

pilosa import -i i -f f data.csv
```
where `data.csv` contains:
```
1,1
1,2
1,4
0,4
```
Then check both rows:
```
curl -X POST http://localhost:10101/index/i/query -d 'Row(f=true)'
{"results":[{"attrs":{},"columns":[1,2,4]}]}

curl -X POST http://localhost:10101/index/i/query -d 'Row(f=false)'
{"results":[{"attrs":{},"columns":[4]}]}
```
Notice that column `4` is both `true` and `false`.

### PR DESCRIPTION
**Pull request by travisturner**
## Overview

This PR ensures that data imported into a `mutex` field is handled correctly (i.e. only allow one row per column).

Fixes #1652 
(This PR addresses the `mutex` portion of #1652. The `bool` will be handled separately along with the PR that introduces `bool` fields.)

## Pull request checklist

- [x] I have read the [contributing guide](https://github.com/pilosa/pilosa/blob/master/CONTRIBUTING.md).
- [x] I have agreed to the [Contributor License Agreement](https://cla-assistant.io/pilosa/pilosa).
- [ ] I have updated the [documentation](https://github.com/pilosa/pilosa/tree/master/docs).
- [x] I have resolved any merge conflicts.
- [x] I have included tests that cover my changes.
- [x] All new and existing tests pass.

## Code review checklist
This is the checklist that the reviewer will follow while reviewing your pull request. You do not need to do anything with this checklist, but be aware of what the reviewer will be looking for.

- [ ] Ensure that any changes to external docs have been included in this pull request.
- [ ] If the changes require that minor/major versions need to be updated, tag the PR appropriately.
- [ ] Ensure the new code is [properly commented](https://github.com/golang/go/wiki/CodeReviewComments#doc-comments) and follows [Idiomatic Go](https://dmitri.shuralyov.com/idiomatic-go).
- [ ] Check that tests have been written and that they cover the new functionality.
- [ ] Run tests and ensure they pass.
- [ ] Build and run the code, performing any applicable integration testing.

### CODE REVIEW

File: fragment.go [hunk 1]
```diff
@@ -1389,6 +1399,94 @@ func (f *fragment) bulkImport(rowIDs, columnIDs []uint64) error {
...
+			if err != nil {
+				return err
+			}
+
+			// Reduce the StatsD rate for high volume stats
+			f.stats.Count("ImportBit", 1, 0.0001)
+
+			// import optimization to avoid linear foreach calls
+			// slight risk of concurrent cache counter being off but
+			// no real danger
```
Comment (jaffee) [inline fragment.go]: can we expunge this comment from the face of the earth? does anyone truly know its arcane meaning?

Comment (tgruben) [reply fragment.go]: how many PR's you gonna comment on this comment?

Comment (travisturner) [reply fragment.go]: I think this comment should be something like:
```
`rowSet` maintains the set of rowIDs present in this import.
It allows the cache to be updated once per row, instead of once
per bit. In doing this, there is a slight risk of the cache counter
being off due to the fact that there may be multiple updates
to the row data before the cache is updated.
```

Comment (travisturner) [reply fragment.go]: With that said, is there a possibility of something concurrently accessing the cache during an import? It seems like the write lock on the fragment would prevent that.
