### PR TITLE
[fix] make sure to unmap containers before modifying

### LINKED ISSUE #1874: UnionInPlace disregards container `mapped` flag causing `fatal error: fault`
The roaring UnionInPlace method will, in some cases, write to a container's data (e.g. the bitmap data) without checking to see if the container is mapped (meaning that the data slice is actually pointing to a region of mmapped data).

This seems to be the case in `unionBitmapArrayInPlace`, `unionBitmapRunInPlace`, and `unionBitmapBitmapInPlace`. Adding `a.unmap()` at the beginning of each of these methods appears to solve the problem, so this ticket is mostly just to document the problem in case anyone comes across it or something similar in the future.

If one creates a fragment and puts some data into it, then tries to do e.g. `f.storage.UnionInPlace(<newBitmap>)`, it's possible to cause something like: 

```
unexpected fault address 0x5519b58
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x5519b58 pc=0x416e8ca]

goroutine 21 [running]:
runtime.throw(0x48eef69, 0x5)
	/usr/local/Cellar/go/1.11.4/libexec/src/runtime/panic.go:608 +0x72 fp=0xc00006eb08 sp=0xc00006ead8 pc=0x402ddb2
runtime.sigpanic()
	/usr/local/Cellar/go/1.11.4/libexec/src/runtime/signal_unix.go:387 +0x2d7 fp=0xc00006eb58 sp=0xc00006eb08 pc=0x4043b47
github.com/pilosa/pilosa/roaring.unionBitmapArrayInPlace(0xc0000f4e10, 0xc0000f5360)
	/Users/jaffee/go/src/github.com/pilosa/pilosa/roaring/roaring.go:2917 +0x2a fp=0xc00006eb68 sp=0xc00006eb58 pc=0x416e8ca
github.com/pilosa/pilosa/roaring.(*Bitmap).unionInPlace(0xc0001a9620, 0xc00006ef08, 0x1, 0x1)
	/Users/jaffee/go/src/github.com/pilosa/pilosa/roaring/roaring.go:723 +0x54c fp=0xc00006ee20 sp=0xc00006eb68 pc=0x4161e3c
github.com/pilosa/pilosa/roaring.(*Bitmap).UnionInPlace(0xc0001a9620, 0xc00006ef08, 0x1, 0x1)
	/Users/jaffee/go/src/github.com/pilosa/pilosa/roaring/roaring.go:479 +0x49 fp=0xc00006ee50 sp=0xc00006ee20 pc=0x4161109
github.com/pilosa/pilosa.TestImportPositionsFunky(0xc0001bc200)
	/Users/jaffee/go/src/github.com/pilosa/pilosa/fragment_internal_test.go:2702 +0x44d fp=0xc00006efa8 sp=0xc00006ee50 pc=0x44e2b8d
testing.tRunner(0xc0001bc200, 0x4926350)
	/usr/local/Cellar/go/1.11.4/libexec/src/testing/testing.go:827 +0xbf fp=0xc00006efd0 sp=0xc00006efa8 pc=0x40f51cf
runtime.goexit()
	/usr/local/Cellar/go/1.11.4/libexec/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc00006efd8 sp=0xc00006efd0 pc=0x405de81
created by testing.(*T).Run
	/usr/local/Cellar/go/1.11.4/libexec/src/testing/testing.go:878 +0x35c

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0001bc200, 0x4900d26, 0x18, 0x4926350, 0x407e001)
	/usr/local/Cellar/go/1.11.4/libexec/src/testing/testing.go:879 +0x383
testing.runTests.func1(0xc0001bc100)
	/usr/local/Cellar/go/1.11.4/libexec/src/testing/testing.go:1119 +0x78
testing.tRunner(0xc0001bc100, 0xc00018fe08)
	/usr/local/Cellar/go/1.11.4/libexec/src/testing/testing.go:827 +0xbf
testing.runTests(0xc0000d53a0, 0x4f5c160, 0xb0, 0xb0, 0x400db8f)
	/usr/local/Cellar/go/1.11.4/libexec/src/testing/testing.go:1117 +0x2aa
testing.(*M).Run(0xc0001ce180, 0x0)
	/usr/local/Cellar/go/1.11.4/libexec/src/testing/testing.go:1034 +0x165
main.main()
	_testmain.go:438 +0x13d

goroutine 19 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/Cellar/go/1.11.4/libexec/src/runtime/sigqueue.go:139 +0x9f
os/signal.loop()
	/usr/local/Cellar/go/1.11.4/libexec/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/local/Cellar/go/1.11.4/libexec/src/os/signal/signal_unix.go:29 +0x41
exit status 2
FAIL	github.com/pilosa/pilosa	0.154s
```

A test case which should reproduce this is: 
```
func TestUnionInPlaceMapped(t *testing.T) {
	f := mustOpenFragment("i", "f", "v", 0, CacheTypeNone)
	defer f.Clean(t)
	r0 := rand.New(rand.NewSource(2))
	r1 := rand.New(rand.NewSource(1))
	data0 := randPositions(65321, r0)
	setBM := roaring.NewBitmap()
	setBM.OpWriter = nil
	setBM.AddN(data0...)
	unprotectedWriteToFragment(f, setBM)
	data1 := randPositions(9, r1)
	setBM2 := roaring.NewBitmap()
	setBM2.OpWriter = nil
	setBM2.AddN(data1...)

	f.storage.UnionInPlace(setBM2)
}

func randPositions(n int, r *rand.Rand) []uint64 {
	ret := make([]uint64, n)
	for i := 0; i < n; i++ {
		ret[i] = uint64(r.Int63n(ShardWidth))
	}
	return ret
}
```

### PR DESCRIPTION
**Pull request by jaffee**
## Overview

Fixes #1874 

## Pull request checklist

- [ ] I have read the [contributing guide](https://github.com/pilosa/pilosa/blob/master/CONTRIBUTING.md).
- [ ] I have agreed to the [Contributor License Agreement](https://cla-assistant.io/pilosa/pilosa).
- [ ] I have updated the [documentation](https://github.com/pilosa/pilosa/tree/master/docs).
- [ ] I have resolved any merge conflicts.
- [ ] I have included tests that cover my changes.
- [ ] All new and existing tests pass.

## Code review checklist
This is the checklist that the reviewer will follow while reviewing your pull request. You do not need to do anything with this checklist, but be aware of what the reviewer will be looking for.

- [ ] Ensure that any changes to external docs have been included in this pull request.
- [ ] If the changes require that minor/major versions need to be updated, tag the PR appropriately.
- [ ] Ensure the new code is [properly commented](https://github.com/golang/go/wiki/CodeReviewComments#doc-comments) and follows [Idiomatic Go](https://dmitri.shuralyov.com/idiomatic-go).
- [ ] Check that tests have been written and that they cover the new functionality.
- [ ] Run tests and ensure they pass.
- [ ] Build and run the code, performing any applicable integration testing.

### CODE REVIEW

File: fragment_internal_test.go [hunk 1]
```diff
@@ -2572,3 +2572,29 @@ func TestFragmentRowIterator(t *testing.T) {
...
+	setBM.OpWriter = nil
+	setBM.Add(data0...)
+	unprotectedWriteToFragment(f, setBM)
+	data1 := randPositions(1000000, r1)
+	setBM2 := roaring.NewBitmap()
+	setBM2.OpWriter = nil
+	setBM2.Add(data1...)
+
+	f.storage.UnionInPlace(setBM2)
+}
```
Comment (seebs) [inline fragment_internal_test.go]: It seems to me like we should check the results in some way? But I'm not sure how, since we don't have a direct check for mapping, and the original wasn't mapped.
