### PR TITLE
Fix - prevent anti-entropy and cluster resize from running simultaneously

### LINKED ISSUE #1492: Prevent cluster resize and anti-entropy from running at the same time
### Description
If a cluster resize event occurs, we need to stop any ongoing anti-entropy (on all nodes in the cluster) before performing the resize. Ideally, we don't wait for anti-entropy to stop on its own, rather we force it to stop, then proceed with the resize as soon as possible.

There is a partial attempt at addressing this in #1202, but that only considered anti-entropy running on the local node, whereas all nodes in the cluster need to be considered.

### PR DESCRIPTION
**Pull request by jaffee**
## Overview

Cluster resize stops any running anti entropy tasks before it can begin. Anti-entropy can't start running while cluster is in state RESIZING.

I wrote a few tests for this, but doing more thorough tests is quite difficult for these components. I started down the path of trying to stress test it (running lots of resizes over significant data while AE interval is set very low), but I think I've triggered some unrelated bugs.

See if you think it'd be acceptable to merge this without any additional tests for now, and I'll work on the stress tests at least in a separate PR.

Note that many of the changed lines are from renaming `cluster.nodes` - this came about due to a race condition in API.Nodes.

Fixes #1492 

## Pull request checklist

- [ ] I have read the [contributing guide](https://github.com/pilosa/pilosa/blob/master/CONTRIBUTING.md).
- [ ] I have agreed to the [Contributor License Agreement](https://cla-assistant.io/pilosa/pilosa).
- [ ] I have updated the [documentation](https://github.com/pilosa/pilosa/tree/master/docs).
- [ ] I have resolved any merge conflicts.
- [ ] I have included tests that cover my changes.
- [ ] All new and existing tests pass.

## Code review checklist
This is the checklist that the reviewer will follow while reviewing your pull request. You do not need to do anything with this checklist, but be aware of what the reviewer will be looking for.

- [ ] Ensure that any changes to external docs have been included in this pull request.
- [ ] If the changes require that minor/major versions need to be updated, tag the PR appropriately.
- [ ] Ensure the new code is [properly commented](https://github.com/golang/go/wiki/CodeReviewComments#doc-comments) and follows [Idiomatic Go](https://dmitri.shuralyov.com/idiomatic-go).
- [ ] Check that tests have been written and that they cover the new functionality.
- [ ] Run tests and ensure they pass.
- [ ] Build and run the code, performing any applicable integration testing.

### CODE REVIEW

**Comment by jaffee** [comment]
bump @travisturner

File: cluster_internal_test.go [hunk 1]
```diff
@@ -804,13 +805,71 @@ func TestCluster_ResizeStates(t *testing.T) {
...
+		c := newCluster()
+		c.initializeAntiEntropy()
+		ch := make(chan struct{})
+		go func() {
+			c.abortAntiEntropy()
+			close(ch)
+		}()
+		select {
+		case <-ch:
+			t.Fatalf("aborting anti entropy on an initialized didn't block")
```
Comment (travisturner) [inline cluster_internal_test.go]: i think this error message is missing a word, perhaps "initialized cluster"?
