### PR TITLE
Fix filter calls in GroupBy not being translated

### LINKED ISSUE #1967: Group by filter doesn't work with field string keys
### What's going wrong?
When running a group by query with a filter expression providing a string key for in the field returns the following error:

`{"error":"executing: executing group by filter for shard 0: Row() error with arg for row: could not convert x of type string to uint64 in Call.UintArg"}`

### What was expected?

A normal group count response with the results filtered based on the supplied expression, similar to:

`{"results":[[{"group":[{"field":"test","rowKey":"y"},{"field":"test2","rowKey":"y"}],"count":1}]]}`

### Steps to reproduce the behavior

1. Create an index with string keys
1. Create a couple of fields with string keys
1. Add some rows
1. Run a group by query similar to  `GroupBy(Rows(field='test'),Rows(field='test2'), filter=Row(test='x'))`

### Information about your environment (OS/architecture, CPU, RAM, cluster/solo, configuration, etc.)

Version 1.2.0

Solo server on Docker in MacOS

### PR DESCRIPTION
**Pull request by jaffee**
## Overview

Fixes #1967 

## Pull request checklist

- [ ] I have read the [contributing guide](https://github.com/pilosa/pilosa/blob/master/CONTRIBUTING.md).
- [ ] I have agreed to the [Contributor License Agreement](https://cla-assistant.io/pilosa/pilosa).
- [ ] I have updated the [documentation](https://github.com/pilosa/pilosa/tree/master/docs).
- [ ] I have resolved any merge conflicts.
- [ ] I have included tests that cover my changes.
- [ ] All new and existing tests pass.
- [ ] Make sure PR title conforms to convention in CHANGELOG.md.
- [ ] Add appropriate changelog label to PR (if applicable).

## Code review checklist
This is the checklist that the reviewer will follow while reviewing your pull request. You do not need to do anything with this checklist, but be aware of what the reviewer will be looking for.

- [ ] Ensure that any changes to external docs have been included in this pull request.
- [ ] If the changes require that minor/major versions need to be updated, tag the PR appropriately.
- [ ] Ensure the new code is [properly commented](https://github.com/golang/go/wiki/CodeReviewComments#doc-comments) and follows [Idiomatic Go](https://dmitri.shuralyov.com/idiomatic-go).
- [ ] Check that tests have been written and that they cover the new functionality.
- [ ] Run tests and ensure they pass.
- [ ] Build and run the code, performing any applicable integration testing.
- [ ] Make sure PR title conforms to convention in CHANGELOG.md.
- [ ] Make sure PR is tagged with appropriate changelog label.

### CODE REVIEW

File: executor_test.go [hunk 1]
```diff
@@ -3243,7 +3243,56 @@ func TestExecutor_Execute_Query_Error(t *testing.T) {
...
+				Query: tst.query,
+			})
+			if err != nil {
+				t.Fatalf("got an error %v", err)
+			}
+			results := r.Results[0].([]pilosa.GroupCount)
+			test.CheckGroupBy(t, tst.expected, results)
+		})
+	}
 }
```
Comment (benbjohnson) [inline executor_test.go]: I personally don't like table tests—they make all the error line numbers show up in the same line and they're just more difficult to debug in general. The actual test body isn't very large either so you could expand this into two separate subtests for probably the same number of lines.

Comment (jaffee) [reply executor_test.go]: They are a bit easier when using the `t.Run` subtest functionality—*if* you give them a descriptive name. In most cases I name them with their index which works fine until you have more than 5 or so, and then it's a bit tough to figure out which one failed.

I like that they encourage adding new cases since it's pretty low effort, but I do think we could do a better job of naming each case to aid in debugging.

We should probably add some more verbiage in CONTRIBUTING around how to write tests, and how our tests are organized. We have enough table tests right now that I don't think we'd want to step away from that pattern, but 🤷‍♂ I'm open to it.
