### PR TITLE
Fixed out of bounds panic to show error

### LINKED ISSUE #1971: PQL panics when int64 max is exceeded
### What's going wrong?
Values above (int64 max value) `9223372036854775807` causes PQL to panic. e.g. 
`TopN(language, n=9223372036854775807)`
`Row(stargazer=9223372036854775808)`

### What was expected?
Error message, instead of a panic.

### Steps to reproduce the behavior
See above.

### Information about your environment (OS/architecture, CPU, RAM, cluster/solo, configuration, etc.)
N/A

### PR DESCRIPTION
**Pull request by hackskills**
## Overview

Fixes PQL to return error when int64 max is exceeded instead of panicking.

Fixes #1971 

## Pull request checklist

- [x] I have read the [contributing guide](https://github.com/pilosa/pilosa/blob/master/CONTRIBUTING.md).
- [x] I have agreed to the [Contributor License Agreement](https://cla-assistant.io/pilosa/pilosa).
- [ ] I have updated the [documentation](https://github.com/pilosa/pilosa/tree/master/docs).
- [ ] I have resolved any merge conflicts.
- [x] I have included tests that cover my changes.
- [x] All new and existing tests pass.
- [x] Make sure PR title conforms to convention in CHANGELOG.md.
- [ ] Add appropriate changelog label to PR (if applicable).

## Code review checklist
This is the checklist that the reviewer will follow while reviewing your pull request. You do not need to do anything with this checklist, but be aware of what the reviewer will be looking for.

- [ ] Ensure that any changes to external docs have been included in this pull request.
- [ ] If the changes require that minor/major versions need to be updated, tag the PR appropriately.
- [ ] Ensure the new code is [properly commented](https://github.com/golang/go/wiki/CodeReviewComments#doc-comments) and follows [Idiomatic Go](https://dmitri.shuralyov.com/idiomatic-go).
- [ ] Check that tests have been written and that they cover the new functionality.
- [ ] Run tests and ensure they pass.
- [ ] Build and run the code, performing any applicable integration testing.
- [ ] Make sure PR title conforms to convention in CHANGELOG.md.
- [ ] Make sure PR is tagged with appropriate changelog label.

### CODE REVIEW

File: pql/pqlpeg_test.go [hunk 1]
```diff
@@ -333,6 +333,12 @@ func TestPEGErrors(t *testing.T) {
 		{
 			name:  "RangeTimeOneStamp",
 			input: "Row(a=4, 2010-07-04T00:00)"},
+        {
```
Comment (jaffee) [inline pql/pqlpeg_test.go]: I think there are some spacing issues here. You'll need to make sure that your editor is configured to run `gofmt` on save. That will make sure that tabs are used in the correct places and all the formatting is correct.

File: pql/parser.go [hunk 2]
```diff
@@ -28,6 +28,7 @@ const timeFormat = "2006-01-02T15:04"
 
 // duplicateArgErrorMessage is used as an error string in the parser.
 const duplicateArgErrorMessage = "duplicate argument provided"
+const parsingIntErrorMessage = "out of bounds"
```
Comment (alanbernstein) [inline pql/parser.go]: This is minor, and I'm not sure if we have any solid conventions about this, but I'd suggest matching the name and message of this error, maybe `outOfBoundsErrorMessage`. See https://github.com/pilosa/pilosa/blob/master/pilosa.go#L26 for the de facto convention.

File: pql/parser.go [hunk 3]
```diff
@@ -26,8 +26,9 @@ import (
 // timeFormat is the go-style time format used to parse string dates.
 const timeFormat = "2006-01-02T15:04"
 
-// duplicateArgErrorMessage is used as an error string in the parser.
+// error strings in the parser
 const duplicateArgErrorMessage = "duplicate argument provided"
+const outOfBoundsErrorMessage = "out of bounds"
```
Comment (jaffee) [inline pql/parser.go]: I think the text of the error could be a bit more descriptive: "integer is not in signed 64-bit range" and then call the error message `intOutOfRangeError` maybe.

File: pql/parser.go [hunk 4]
```diff
@@ -72,7 +72,8 @@ func (p *parser) Parse() (*Query, error) {
 		p.Execute()
 	}()
 	if v != nil {
-		if strings.HasPrefix(v.(string), duplicateArgErrorMessage) || strings.HasPrefix(v.(string), outOfBoundsErrorMessage) {
+		errorMessage := v.(string)
```
Comment (jaffee) [inline pql/parser.go]: ah, what we can do here to be a little bit more robust to this kind of problem in the future is:

```
errorMessage, ok := v.(string)
if !ok {
    return nil, fmt.Errorf("unexpected parser error of type %T: %[1]v", v)
}
```
