### PR TITLE
Default gossip seed should be empty instead of local bind address

### LINKED ISSUE #1172: Failure to connect to gossip seed with default config on single-node cluster (no route to host)
### Expected behavior

Starting "pilosa server" with no arguments should bring up a running single-node cluster without logged errors.

### Actual behavior

Since default gossip seed is localhost:14000, it tries to connect to that even with a single node cluster. The following error is logged (does not seem to affect performance):
```
...
2018/03/19 15:00:04 [DEBUG] memberlist: Failed to join fe80::1: dial tcp [fe80::1]:14000: connect: no route to host
...
```
### Steps to reproduce the behavior

Run `pilosa server` with no config.

### PR DESCRIPTION
**Pull request by travisturner**
## Overview

There is no need to set the gossip seed to the local node's bind address (e.g. in the case of a one-node cluster). This PR removes that default, and moves the logic to the `Seeds()` method which is actually only used for testing.

Fixes #1172 

## Pull request checklist

- [x] I have read the [contributing guide](https://github.com/pilosa/pilosa/blob/master/CONTRIBUTING.md).
- [x] I have agreed to the [Contributor License Agreement](https://cla-assistant.io/pilosa/pilosa).
- [x] I have updated the [documentation](https://github.com/pilosa/pilosa/tree/master/docs).
- [x] I have resolved any merge conflicts.
- [ ] I have included tests that cover my changes.
- [x] All new and existing tests pass.

## Code review checklist
This is the checklist that the reviewer will follow while reviewing your pull request. You do not need to do anything with this checklist, but be aware of what the reviewer will be looking for.

- [ ] Ensure that any changes to external docs have been included in this pull request.
- [ ] If the changes require that minor/major versions need to be updated, tag the PR appropriately.
- [ ] Ensure the new code is [properly commented](https://github.com/golang/go/wiki/CodeReviewComments#doc-comments) and follows [Idiomatic Go](https://dmitri.shuralyov.com/idiomatic-go).
- [ ] Check that tests have been written and that they cover the new functionality.
- [ ] Run tests and ensure they pass.
- [ ] Build and run the code, performing any applicable integration testing.

### CODE REVIEW

File: gossip/gossip.go [hunk 1]
```diff
@@ -63,6 +63,9 @@ func (g *GossipMemberSet) Start(h pilosa.BroadcastHandler) error {
 
 // Seeds returns the gossipSeeds determined by the config.
```
Comment (codysoyland) [inline gossip/gossip.go]: Might be good to clarify the function comment to something like: "Seeds returns a list of usable gossip seeds for this cluster. If no seeds are configured, return the gossip listener of this server."

Or otherwise comment on the `if` statement to explain it.

Comment (travisturner) [reply gossip/gossip.go]: Thanks @codysoyland, that was definitely confusing. I pushed a commit which renames that method and doesn't use `gossipSeeds` at all. It's really only there for one test. Ideally we could get ride of that logic completely, but for now I just tried to make it more clear what was happening.

Comment (codysoyland) [reply gossip/gossip.go]: The latest commit is great 👍
